spring:
  application:
    name: liquibase-service
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/db/changelog/changelog-master.xml

logging:
  level:
    liquibase: DEBUG
    org.springframework: DEBUG
